spring:
  application:
    name: ai-travel-planner
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        retry:
          enabled: true
  data:
    redis:
      host: 127.0.0.1
      database: 4
      password: 123456
      port: 6379
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: gpt-3.5-turbo
server:
    port: 8088